// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Workly.Infrastructure.Persistence;

#nullable disable

namespace Workly.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorklyDbContext))]
    partial class WorklyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Workly.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_activity_logs");

                    b.HasIndex("OrganizationId", "ActorId")
                        .HasDatabaseName("ix_activity_logs_organization_id_actor_id");

                    b.HasIndex("OrganizationId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_activity_logs_organization_id_created_at");

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("Workly.Domain.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("character varying(12000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<bool>("Pinned")
                        .HasColumnType("boolean")
                        .HasColumnName("pinned");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_announcements");

                    b.HasIndex("OrganizationId", "AuthorId")
                        .HasDatabaseName("ix_announcements_organization_id_author_id");

                    b.HasIndex("OrganizationId", "Pinned", "CreatedAt")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_announcements_organization_id_pinned_created_at");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("Workly.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_departments_organization_id_id");

                    b.HasIndex("OrganizationId", "ManagerId")
                        .HasDatabaseName("ix_departments_organization_id_manager_id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_departments_organization_id_name");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Workly.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedById")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_invitations_token_hash");

                    b.HasIndex("OrganizationId", "DepartmentId")
                        .HasDatabaseName("ix_invitations_organization_id_department_id");

                    b.HasIndex("OrganizationId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_invitations_organization_id_email")
                        .HasFilter("accepted_at IS NULL AND revoked_at IS NULL");

                    b.HasIndex("OrganizationId", "InvitedById")
                        .HasDatabaseName("ix_invitations_organization_id_invited_by_id");

                    b.ToTable("invitations", null, t =>
                        {
                            t.HasCheckConstraint("ck_invitations_role", "role IN ('employee', 'manager', 'hr', 'admin')");
                        });
                });

            modelBuilder.Entity("Workly.Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedById")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_id");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("decision_note");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_leave_requests");

                    b.HasIndex("OrganizationId", "DecidedById")
                        .HasDatabaseName("ix_leave_requests_organization_id_decided_by_id");

                    b.HasIndex("OrganizationId", "MemberId")
                        .HasDatabaseName("ix_leave_requests_organization_id_member_id");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_leave_requests_organization_id_status");

                    b.HasIndex("OrganizationId", "StartDate", "EndDate")
                        .HasDatabaseName("ix_leave_requests_organization_id_start_date_end_date")
                        .HasFilter("status = 'approved'");

                    b.ToTable("leave_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_leave_requests_dates", "end_date >= start_date");

                            t.HasCheckConstraint("ck_leave_requests_status", "status IN ('pending', 'approved', 'rejected', 'cancelled')");

                            t.HasCheckConstraint("ck_leave_requests_type", "type IN ('annual', 'sick', 'personal', 'other')");
                        });
                });

            modelBuilder.Entity("Workly.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_slug");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Workly.Domain.Entities.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("job_title");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_members");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_organization_members_organization_id_id");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_members_organization_id")
                        .HasFilter("role = 'owner' AND status = 'active'");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_members_user_id");

                    b.HasIndex("OrganizationId", "DepartmentId")
                        .HasDatabaseName("ix_organization_members_organization_id_department_id");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_members_organization_id_user_id");

                    b.ToTable("organization_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_organization_members_role", "role IN ('employee', 'manager', 'hr', 'admin', 'owner')");

                            t.HasCheckConstraint("ck_organization_members_status", "status IN ('active', 'removed')");
                        });
                });

            modelBuilder.Entity("Workly.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_projects_organization_id_id");

                    b.HasIndex("OrganizationId", "CreatedById")
                        .HasDatabaseName("ix_projects_organization_id_created_by_id");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_projects_organization_id_status");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasCheckConstraint("ck_projects_dates", "due_date IS NULL OR start_date IS NULL OR due_date >= start_date");

                            t.HasCheckConstraint("ck_projects_status", "status IN ('active', 'on_hold', 'completed', 'archived')");
                        });
                });

            modelBuilder.Entity("Workly.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("ProjectId", "MemberId")
                        .HasName("pk_project_members");

                    b.HasIndex("OrganizationId", "MemberId")
                        .HasDatabaseName("ix_project_members_organization_id_member_id");

                    b.HasIndex("OrganizationId", "ProjectId")
                        .HasDatabaseName("ix_project_members_organization_id_project_id");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("Workly.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ReplacedById")
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Workly.Domain.Entities.TaskComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_task_comments");

                    b.HasIndex("OrganizationId", "AuthorId")
                        .HasDatabaseName("ix_task_comments_organization_id_author_id");

                    b.HasIndex("OrganizationId", "TaskId")
                        .HasDatabaseName("ix_task_comments_organization_id_task_id");

                    b.ToTable("task_comments", (string)null);
                });

            modelBuilder.Entity("Workly.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Workly.Domain.Entities.WorkTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_tasks_organization_id_id");

                    b.HasIndex("OrganizationId", "DueDate")
                        .HasDatabaseName("ix_tasks_organization_id_due_date")
                        .HasFilter("status <> 'done'");

                    b.HasIndex("OrganizationId", "ProjectId")
                        .HasDatabaseName("ix_tasks_organization_id_project_id");

                    b.HasIndex("OrganizationId", "AssigneeId", "Status")
                        .HasDatabaseName("ix_tasks_organization_id_assignee_id_status");

                    b.HasIndex("ProjectId", "Status", "Position")
                        .HasDatabaseName("ix_tasks_project_id_status_position");

                    b.ToTable("tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_tasks_position", "position >= 0");

                            t.HasCheckConstraint("ck_tasks_priority", "priority IN ('low', 'medium', 'high')");

                            t.HasCheckConstraint("ck_tasks_status", "status IN ('todo', 'in_progress', 'done')");
                        });
                });

            modelBuilder.Entity("Workly.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("Workly.Domain.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_logs_organizations_organization_id");

                    b.HasOne("Workly.Domain.Entities.OrganizationMember", "Actor")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ActorId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_activity_logs_organization_members_organization_id_actor_id");

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("Workly.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("Workly.Domain.Entities.OrganizationMember", "Author")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "AuthorId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_announcements_organization_members_organization_id_author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Workly.Domain.Entities.Department", b =>
                {
                    b.HasOne("Workly.Domain.Entities.Organization", "Organization")
                        .WithMany("Departments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_departments_organizations_organization_id");

                    b.HasOne("Workly.Domain.Entities.OrganizationMember", "Manager")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ManagerId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_departments_organization_members_organization_id_manager_id");

                    b.Navigation("Manager");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Workly.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("Workly.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "DepartmentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_invitations_departments_organization_id_department_id");

                    b.HasOne("Workly.Domain.Entities.OrganizationMember", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "InvitedById")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_organization_members_organization_id_invited_by");

                    b.Navigation("Department");

                    b.Navigation("InvitedBy");
                });

            modelBuilder.Entity("Workly.Domain.Entities.LeaveRequest", b =>
                {
                    b.HasOne("Workly.Domain.Entities.OrganizationMember", "DecidedBy")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "DecidedById")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_leave_requests_organization_members_organization_id_decided");

                    b.HasOne("Workly.Domain.Entities.OrganizationMember", "Member")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "MemberId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leave_requests_organization_members_organization_id_member_");

                    b.Navigation("DecidedBy");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Workly.Domain.Entities.OrganizationMember", b =>
                {
                    b.HasOne("Workly.Domain.Entities.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_members_organizations_organization_id");

                    b.HasOne("Workly.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_members_users_user_id");

                    b.HasOne("Workly.Domain.Entities.Department", "Department")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId", "DepartmentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_organization_members_departments_organization_id_department");

                    b.Navigation("Department");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workly.Domain.Entities.Project", b =>
                {
                    b.HasOne("Workly.Domain.Entities.Organization", "Organization")
                        .WithMany("Projects")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_organizations_organization_id");

                    b.HasOne("Workly.Domain.Entities.OrganizationMember", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CreatedById")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_organization_members_organization_id_created_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Workly.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("Workly.Domain.Entities.OrganizationMember", "Member")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "MemberId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_organization_members_organization_id_member");

                    b.HasOne("Workly.Domain.Entities.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId", "ProjectId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_projects_organization_id_project_id");

                    b.Navigation("Member");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Workly.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Workly.Domain.Entities.RefreshToken", "ReplacedBy")
                        .WithMany()
                        .HasForeignKey("ReplacedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by_id");

                    b.HasOne("Workly.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("ReplacedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workly.Domain.Entities.TaskComment", b =>
                {
                    b.HasOne("Workly.Domain.Entities.OrganizationMember", "Author")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "AuthorId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_comments_organization_members_organization_id_author_id");

                    b.HasOne("Workly.Domain.Entities.WorkTask", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("OrganizationId", "TaskId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_comments_tasks_organization_id_task_id");

                    b.Navigation("Author");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Workly.Domain.Entities.WorkTask", b =>
                {
                    b.HasOne("Workly.Domain.Entities.OrganizationMember", "Assignee")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "AssigneeId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tasks_organization_members_organization_id_assignee_id");

                    b.HasOne("Workly.Domain.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("OrganizationId", "ProjectId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_projects_organization_id_project_id");

                    b.Navigation("Assignee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Workly.Domain.Entities.Department", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Workly.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Members");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Workly.Domain.Entities.Project", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Workly.Domain.Entities.User", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Workly.Domain.Entities.WorkTask", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
