<script setup lang="ts">
import { Plus, Save, Trash2 } from '@lucide/vue'
import type { Member, Project, WorkItem } from '~/types/operations'
import { getAuthErrorMessage } from '~/utils/auth'
definePageMeta({ middleware: 'auth' })
const route = useRoute(); const { request } = useOperations(); const tasks = ref<WorkItem[]>([]); const projects = ref<Project[]>([]); const people = ref<Member[]>([]); const loading = ref(true); const error = ref('')
const form = reactive({ projectId: '', title: '', description: '', status: 'todo', priority: 'medium', assigneeId: '', dueDate: '', position: 0 })
const payload = (task: typeof form | WorkItem) => ({ projectId: task.projectId, title: task.title, description: task.description || null, status: task.status, priority: task.priority, assigneeId: task.assigneeId || null, dueDate: task.dueDate || null, position: task.position })
const load = async () => { loading.value = true; try { [tasks.value, projects.value, people.value] = await Promise.all([request<WorkItem[]>(`tasks${route.query.project ? `?projectId=${route.query.project}` : ''}`), request<Project[]>('projects'), request<Member[]>('people')]); form.projectId ||= String(route.query.project || projects.value[0]?.id || '') } catch (cause) { error.value = getAuthErrorMessage(cause) } finally { loading.value = false } }
onMounted(load)
const create = async () => { try { await request<WorkItem>('tasks', { method: 'POST', body: payload(form) }); Object.assign(form, { projectId: form.projectId, title: '', description: '', status: 'todo', priority: 'medium', assigneeId: '', dueDate: '', position: 0 }); await load() } catch (cause) { error.value = getAuthErrorMessage(cause) } }
const save = async (task: WorkItem) => { try { await request<WorkItem>(`tasks/${task.id}`, { method: 'PATCH', body: payload(task) }); await load() } catch (cause) { error.value = getAuthErrorMessage(cause) } }
const remove = async (task: WorkItem) => { if (!confirm(`Delete ${task.title}?`)) return; try { await request<unknown>(`tasks/${task.id}`, { method: 'DELETE' }); await load() } catch (cause) { error.value = getAuthErrorMessage(cause) } }
</script>
<template><div class="resource-page"><header class="page-header"><div><p class="eyebrow">Work management</p><h1>Tasks</h1><p>Create, assign, prioritize, and move work through its lifecycle.</p></div></header><p v-if="error" class="form-alert">{{ error }}</p>
  <form class="card resource-form" @submit.prevent="create"><h2>Create task</h2><div class="field-grid field-grid--3"><label>Project<select v-model="form.projectId" required><option value="" disabled>Select project</option><option v-for="project in projects" :key="project.id" :value="project.id">{{ project.name }}</option></select></label><label>Title<input v-model="form.title" required minlength="2"></label><label>Due date<input v-model="form.dueDate" type="date"></label><label>Priority<select v-model="form.priority"><option>low</option><option>medium</option><option>high</option></select></label><label>Assignee<select v-model="form.assigneeId"><option value="">Unassigned</option><option v-for="person in people.filter(p => p.status === 'active')" :key="person.id" :value="person.id">{{ person.name }}</option></select></label></div><label>Description<textarea v-model="form.description" rows="2" /></label><button class="button button--primary" :disabled="!projects.length"><Plus :size="17" /> Create task</button></form>
  <div class="card table-card"><p v-if="loading" class="resource-state">Loading tasks…</p><p v-else-if="tasks.length === 0" class="resource-state">No tasks yet.</p><div v-else class="table-scroll"><table class="data-table"><thead><tr><th>Task</th><th>Project</th><th>Status</th><th>Priority</th><th>Assignee</th><th>Due</th><th /></tr></thead><tbody><tr v-for="task in tasks" :key="task.id"><td><input v-model="task.title"><small>{{ task.description }}</small></td><td>{{ task.projectName }}</td><td><select v-model="task.status"><option>todo</option><option>in-progress</option><option>done</option></select></td><td><select v-model="task.priority"><option>low</option><option>medium</option><option>high</option></select></td><td><select v-model="task.assigneeId"><option :value="null">Unassigned</option><option v-for="person in people.filter(p => p.status === 'active')" :key="person.id" :value="person.id">{{ person.name }}</option></select></td><td><input v-model="task.dueDate" type="date"></td><td><div class="resource-actions"><button class="icon-button" aria-label="Save task" @click="save(task)"><Save :size="16" /></button><button class="icon-button danger-text" aria-label="Delete task" @click="remove(task)"><Trash2 :size="16" /></button></div></td></tr></tbody></table></div></div>
</div></template>
